### Specialized Linear Algebra Libraries

In [1]:
import numpy as np

In [2]:
np.__config__.show()  #to check specialized commands used

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [3]:
b=np.array([-13,9]) #constructing 1D Array
A=np.array([[4,-5],[-2,3]])  #2D Array construction
print (b)

[-13   9]


In [4]:
print(A)

[[ 4 -5]
 [-2  3]]


In [5]:
print(np.ones(4)) #1D Array of Ones

[1. 1. 1. 1.]


In [6]:
print(np.zeros(4)) #1D Array of Zeros

[0. 0. 0. 0.]


In [7]:
print (np.random.randn(4))  #1D array of random normal numbers 

[-1.65298378  0.21410836 -0.22579139 -1.08777163]


In [8]:
print(np.eye(3)) #Creates 3x3 identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
print(np.diag(np.random.randn(3))) #Create diagonal array

[[ 0.83688303  0.          0.        ]
 [ 0.         -1.45173931  0.        ]
 [ 0.          0.         -0.05931024]]


### Indexing into numpy array

In [10]:
A=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
print(A[1,1])

5


In [13]:
print(A[1,:])

[4 5 6]


In [15]:
print(A[1:3,:])

[[4 5 6]
 [7 8 9]]


In [16]:
print(A[1:2,1:2])

[[5]]


In [17]:
print(A[[1,2,3],:])  # select rows 1, 2, and 3

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
print(A[[2,1,2],:])  # select rows 2, 1, and 2

[[7 8 9]
 [4 5 6]
 [7 8 9]]


In [19]:
print(A[[False,True,False,True],:]) #Select 1st and 3rd row

[[ 4  5  6]
 [10 11 12]]


In [20]:
print(A[[2,1,2],[1,2,0]])  # the same as np.array([A[2,1], A[1,2], A[2,0]])

[8 6 7]


In [21]:
A[[2,1,2],:][:,[1,2,0]]

array([[8, 9, 7],
       [5, 6, 4],
       [8, 9, 7]])

### Basic Operations on Array

In [22]:
B = np.array([[1, 1, 1], [1,2,1], [3, 1, 3], [1, 4, 1]])
print(A+B) # add A and B elementwise

[[ 2  3  4]
 [ 5  7  7]
 [10  9 12]
 [11 15 13]]


In [23]:
print(A-B) # subtract A and B elementwise

[[ 0  1  2]
 [ 3  3  5]
 [ 4  7  6]
 [ 9  7 11]]


In [24]:
print(A*B, "\n") # elementwise multiplication, _not_ matrix multiplication
print(A/B, "\n") # elementwise division, _not_ matrix inversion

[[ 1  2  3]
 [ 4 10  6]
 [21  8 27]
 [10 44 12]] 

[[ 1.          2.          3.        ]
 [ 4.          2.5         6.        ]
 [ 2.33333333  8.          3.        ]
 [10.          2.75       12.        ]] 



In [25]:
x = np.array([1,2,3,4])
print(A.T)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [26]:
print(x)

[1 2 3 4]


In [27]:
print(x.T)

[1 2 3 4]


### Broadcasting

In [28]:
A = np.ones((4,3))          # A is 4x3
x = np.array([[1,2,3]])      # x is 1x3
A*x                          # repeat x along dimension 4 (repeat four times), and add to A

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [29]:
x = np.array([[1],[2],[3],[4]])
A*x

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [30]:
x = np.array([1,2,3])
A*x

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [31]:
x = np.array([1,2,3,4])
print(x[:,None])

[[1]
 [2]
 [3]
 [4]]


In [32]:
print(A*x[:,None])

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [33]:
D = np.diag(np.array([1,2,3]))
A @ D #@ is multiplication operator

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

### Linear Algebra Operations

In [34]:
A = np.random.randn(5,4)
C = np.random.randn(4,3)
x = np.random.randn(4)
y = np.random.randn(5)
z = np.random.randn(4)

print(A @ C)       # matrix-matrix multiply (returns 2D array)

[[-2.60953221 -0.75041744  0.90098085]
 [-0.36835286  1.05061512 -1.8757806 ]
 [-1.88863246  1.52964606 -2.16633091]
 [ 0.11668477 -0.5589936  -0.31527041]
 [ 0.64006486 -2.35262397  2.31039408]]


In [36]:
print(A @ x)       # matrix-vector multiply (returns 1D array)

[ 0.6133806  -0.23484147  0.10029718  0.59793827  0.86361359]


In [37]:
print(x @ z)       # inner product (scalar)

-0.35456187809782136


In [38]:
print(A.T @ y, "\n")
print(y.T @ A)

[-2.43675918  4.45493127 -0.32054654  0.77030704] 

[-2.43675918  4.45493127 -0.32054654  0.77030704]


In [39]:
print(y @ A)

[-2.43675918  4.45493127 -0.32054654  0.77030704]


In [42]:
import scipy.sparse  as sp
A=sp.coo_matrix(np.eye(5))
A.todense()

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [43]:
np.asarray(A.todense())

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Order Of Matrix Multiplication Operators

In [44]:
A = np.random.randn(1000,1000)
B = np.random.randn(1000,2000)
x = np.random.randn(2000)
%timeit A @ B @ x  #to find out time taken for specific task

91 ms ± 3.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [45]:
%timeit A@(B@x) #more efficient than the above

1.23 ms ± 8.08 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Inverse And Linear Solves

In [46]:
b = np.array([-13,9])
A = np.array([[4,-5], [-2,3]])

print(np.linalg.inv(A), "\n")   # explicitly form inverse
print(np.linalg.solve(A,b))     # compute solution A^{-1}b

[[1.5 2.5]
 [1.  2. ]] 

[3. 5.]


### Sparse Matrice

In [50]:
values = [2, 4, 1, 3, 1, 1]
row_indices = [1, 3, 2, 0, 3, 1]
column_indices = [0, 0, 1, 2, 2, 3]
A = sp.coo_matrix((values, (row_indices, column_indices)), shape=(4,4))
A
print(A.todense())

[[0 0 3 0]
 [2 0 0 1]
 [0 1 0 0]
 [4 0 1 0]]


In [51]:
print(A.data)
print(A.row)
print(A.col)

[2 4 1 3 1 1]
[1 3 2 0 3 1]
[0 0 1 2 2 3]


In [52]:
B = A.tocsc() #converting to csc format

In [53]:
print(B.data)
print(B.indices) #Array of column indices 
print(B.indptr) #points to row start in indices and data

[2 4 1 3 1 1]
[1 3 2 0 3 1]
[0 2 3 5 6]


Let's create a 1000x1000 sparse matrix with 99.9% sparsity plus an identity matrix.   The precise nature of the matrix isn't important here, we just want to consider the timing.

In [54]:
A = sp.rand(1000,1000, 0.001) + sp.eye(1000)
B = np.asarray(A.todense())
x = np.random.randn(1000)
%timeit A @ x
%timeit B @ x

16.6 µs ± 2.01 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
404 µs ± 9.03 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Here the sparse version is about 50x faster, though of course the speedup will increase with sparsity relative to the dense matrix.

In [56]:
import scipy.sparse.linalg as spla
A = A.tocsc()
%timeit spla.spsolve(A,x)     # only works with CSC or CSR format
%timeit np.linalg.solve(B,x)

1.4 ms ± 16.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
27.3 ms ± 559 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
